---
- name: Removendo /etc/nginx/sites-enabled/default
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Configurando o Nginx
  get_url:
    url: "{{ FILES_BASE_URL }}/nginx_redash_site"
    dest: /etc/nginx/sites-available/redash

- name: Criando link simbolico /etc/nginx/sites-enabled/redash
  file:
    src: /etc/nginx/sites-available/redash
    dest: /etc/nginx/sites-enabled/redash
    state: link
  notify:
    - restart nginx
